// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/aws_storage/awsstorage_service.proto

package awsstorage_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBucketRequest struct {
	Bucketname           string   `protobuf:"bytes,1,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketRequest) Reset()         { *m = CreateBucketRequest{} }
func (m *CreateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBucketRequest) ProtoMessage()    {}
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d83d590e86b97ee, []int{0}
}

func (m *CreateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketRequest.Unmarshal(m, b)
}
func (m *CreateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketRequest.Marshal(b, m, deterministic)
}
func (m *CreateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketRequest.Merge(m, src)
}
func (m *CreateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBucketRequest.Size(m)
}
func (m *CreateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketRequest proto.InternalMessageInfo

func (m *CreateBucketRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

type CreateBucketResponse struct {
	Bucketname           string   `protobuf:"bytes,1,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketResponse) Reset()         { *m = CreateBucketResponse{} }
func (m *CreateBucketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBucketResponse) ProtoMessage()    {}
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d83d590e86b97ee, []int{1}
}

func (m *CreateBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketResponse.Unmarshal(m, b)
}
func (m *CreateBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketResponse.Marshal(b, m, deterministic)
}
func (m *CreateBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketResponse.Merge(m, src)
}
func (m *CreateBucketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBucketResponse.Size(m)
}
func (m *CreateBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketResponse proto.InternalMessageInfo

func (m *CreateBucketResponse) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

type UploadRequest struct {
	Bucketname           string   `protobuf:"bytes,1,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Medianame            string   `protobuf:"bytes,2,opt,name=medianame,proto3" json:"medianame,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Offset               int64    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d83d590e86b97ee, []int{2}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *UploadRequest) GetMedianame() string {
	if m != nil {
		return m.Medianame
	}
	return ""
}

func (m *UploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UploadRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type UploadResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d83d590e86b97ee, []int{3}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UploadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBucketRequest)(nil), "CreateBucketRequest")
	proto.RegisterType((*CreateBucketResponse)(nil), "CreateBucketResponse")
	proto.RegisterType((*UploadRequest)(nil), "UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "UploadResponse")
}

func init() {
	proto.RegisterFile("proto/aws_storage/awsstorage_service.proto", fileDescriptor_4d83d590e86b97ee)
}

var fileDescriptor_4d83d590e86b97ee = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x1b, 0x1b, 0x23, 0x1d, 0x6a, 0x85, 0xb1, 0x96, 0x50, 0x44, 0x42, 0x4e, 0xc1, 0x43,
	0x44, 0x45, 0x6f, 0x1e, 0x8c, 0xe0, 0x0f, 0x08, 0x78, 0x2e, 0xd3, 0x64, 0x1a, 0x82, 0x4d, 0x37,
	0xee, 0x6c, 0x14, 0x2f, 0xfe, 0x76, 0x71, 0x49, 0xb4, 0x81, 0x82, 0xbd, 0xcd, 0x7b, 0xb3, 0xc3,
	0x7b, 0x7c, 0x0b, 0x97, 0xb5, 0x56, 0x46, 0x5d, 0xd1, 0x87, 0x2c, 0xc4, 0x28, 0x4d, 0x05, 0xff,
	0xcc, 0xed, 0xb8, 0x10, 0xd6, 0xef, 0x65, 0xc6, 0xb1, 0x7d, 0x14, 0xde, 0xc1, 0xe9, 0x93, 0x66,
	0x32, 0x9c, 0x34, 0xd9, 0x2b, 0x9b, 0x94, 0xdf, 0x1a, 0x16, 0x83, 0x17, 0x00, 0x4b, 0x6b, 0x6c,
	0xa8, 0x62, 0xdf, 0x09, 0x9c, 0x68, 0x94, 0x6e, 0x39, 0xe1, 0x3d, 0x4c, 0xfb, 0x67, 0x52, 0xab,
	0x8d, 0xf0, 0xbf, 0x77, 0x9f, 0x70, 0xfc, 0x52, 0xaf, 0x15, 0xe5, 0x7b, 0x06, 0xe1, 0x39, 0x8c,
	0x2a, 0xce, 0x4b, 0xb2, 0xeb, 0x03, 0xbb, 0xfe, 0x33, 0x10, 0xc1, 0xcd, 0xc9, 0x90, 0x3f, 0x0c,
	0x9c, 0x68, 0x9c, 0xda, 0x19, 0x67, 0xe0, 0xa9, 0xd5, 0x4a, 0xd8, 0xf8, 0x6e, 0xe0, 0x44, 0xc3,
	0xb4, 0x55, 0x61, 0x02, 0x93, 0x2e, 0xba, 0x2d, 0x3b, 0x03, 0x4f, 0x0c, 0x99, 0x46, 0x6c, 0xee,
	0x61, 0xda, 0x2a, 0xf4, 0xe1, 0xa8, 0x62, 0x11, 0x2a, 0xba, 0xc4, 0x4e, 0xde, 0x7c, 0x01, 0x3c,
	0xfe, 0x92, 0xc4, 0x07, 0x18, 0x67, 0x5b, 0x10, 0x70, 0x1a, 0xef, 0x40, 0x39, 0x3f, 0x8b, 0x77,
	0x91, 0x0a, 0x07, 0x78, 0x0d, 0xd0, 0xd8, 0x42, 0xcf, 0xe5, 0x9a, 0x71, 0x12, 0xf7, 0xc0, 0xcc,
	0x4f, 0xe2, 0x7e, 0xdb, 0x70, 0x10, 0x39, 0x89, 0x07, 0x6e, 0xa1, 0xeb, 0x6c, 0xe9, 0xd9, 0xcf,
	0xbb, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x79, 0xb9, 0x44, 0xea, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AwsstorageClient is the client API for Awsstorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AwsstorageClient interface {
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (Awsstorage_UploadFileClient, error)
}

type awsstorageClient struct {
	cc grpc.ClientConnInterface
}

func NewAwsstorageClient(cc grpc.ClientConnInterface) AwsstorageClient {
	return &awsstorageClient{cc}
}

func (c *awsstorageClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, "/Awsstorage/createBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *awsstorageClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (Awsstorage_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Awsstorage_serviceDesc.Streams[0], "/Awsstorage/uploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &awsstorageUploadFileClient{stream}
	return x, nil
}

type Awsstorage_UploadFileClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type awsstorageUploadFileClient struct {
	grpc.ClientStream
}

func (x *awsstorageUploadFileClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *awsstorageUploadFileClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AwsstorageServer is the server API for Awsstorage service.
type AwsstorageServer interface {
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	UploadFile(Awsstorage_UploadFileServer) error
}

// UnimplementedAwsstorageServer can be embedded to have forward compatible implementations.
type UnimplementedAwsstorageServer struct {
}

func (*UnimplementedAwsstorageServer) CreateBucket(ctx context.Context, req *CreateBucketRequest) (*CreateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (*UnimplementedAwsstorageServer) UploadFile(srv Awsstorage_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}

func RegisterAwsstorageServer(s *grpc.Server, srv AwsstorageServer) {
	s.RegisterService(&_Awsstorage_serviceDesc, srv)
}

func _Awsstorage_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AwsstorageServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Awsstorage/CreateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AwsstorageServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Awsstorage_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AwsstorageServer).UploadFile(&awsstorageUploadFileServer{stream})
}

type Awsstorage_UploadFileServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type awsstorageUploadFileServer struct {
	grpc.ServerStream
}

func (x *awsstorageUploadFileServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *awsstorageUploadFileServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Awsstorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Awsstorage",
	HandlerType: (*AwsstorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createBucket",
			Handler:    _Awsstorage_CreateBucket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "uploadFile",
			Handler:       _Awsstorage_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/aws_storage/awsstorage_service.proto",
}
